## Extracción del Archivo Tratado Eliminación de Columnas Irrelevantes

In [1]:
import pandas as pd

df = pd.read_csv('datos_tratados.csv')

In [2]:
df.head()

,evasion,genero,seniorcitizen,pareja,dependientes,antiguedad,servicio_telefonico,lineas_multiples,servicio_internet,seguridad_online,...,soporte_tecnico,tv_streaming,peliculas_streaming,contrato,facturacion_sin_papel,metodo_pago,cargos_mensuales,cargos_totales,diarias,total_servicios
0,0,1,0,1,1,9,1,0,DSL,0,...,1,1,0,One year,1,Mailed check,65.6,593.30,2.19,4
1,0,0,0,0,0,9,1,1,DSL,0,...,0,0,1,Month-to-month,0,Mailed check,59.9,542.40,2.00,3
2,1,0,0,0,0,4,1,0,Fiber optic,0,...,0,0,0,Month-to-month,1,Electronic check,73.9,280.85,2.46,2
3,1,0,1,1,0,13,1,0,Fiber optic,0,...,0,1,1,Month-to-month,1,Electronic check,98.0,1237.85,3.27,5
4,1,1,1,1,0,3,1,0,Fiber optic,0,...,1,1,0,Month-to-month,1,Mailed check,83.9,267.40,2.80,3

In [9]:
col = df.columns

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7021 entries, 0 to 7020
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   evasion                 7021 non-null   int64
 1   genero                  7021 non-null   int64
 2   seniorcitizen           7021 non-null   int64
 3   pareja                  7021 non-null   int64
 4   dependientes            7021 non-null   int64
 5   antiguedad              7021 non-null   int64
 6   servicio_telefonico     7021 non-null   int64
 7   lineas_multiples        7021 non-null   int64
 8   servicio_internet       7021 non-null   object
 9   seguridad_online        7021 non-null   int64
 10  respaldo_online         7021 non-null   int64
 11  proteccion_dispositivo  7021 non-null   int64
 12  soporte_tecnico         7021 non-null   int64
 13  tv_streaming            7021 non-null   int64
 14  peliculas_streaming     7021 non-null   int64
 15  contrato                7021 non-null   object
 16  facturacion_sin_papel   7021 non-null   int64
 17  metodo_pago             7021 non-null   object
 18  cargos_mensuales        7021 non-null   float64
 19  cargos_totales          7010 non-null   float64
 20  diarias                 7021 non-null   float64
 21  total_servicios         7021 non-null   int64
dtypes: float64(3), int64(16), object(3)
memory usage: 1.2+ MB

## Encoding

In [31]:
columnas_cats = df.select_dtypes(include=['object', 'category']).columns

for col in columnas_cats:
    print(f'{col.upper()}')
    print(df[col].unique())

SERVICIO_INTERNET
['DSL' 'Fiber optic' 'No']
CONTRATO
['One year' 'Month-to-month' 'Two year']
METODO_PAGO
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']

In [34]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, drop='first')

encoded_data = encoder.fit_transform(df[columnas_cats])

encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out())

df = pd.concat([df, encoded_df], axis=1).drop(columns=columnas_cats)

df

,evasion,genero,seniorcitizen,pareja,dependientes,antiguedad,servicio_telefonico,lineas_multiples,seguridad_online,respaldo_online,...,cargos_totales,diarias,total_servicios,servicio_internet_Fiber optic,servicio_internet_No,contrato_One year,contrato_Two year,metodo_pago_Credit card (automatic),metodo_pago_Electronic check,metodo_pago_Mailed check
0,0,1,0,1,1,9,1,0,0,1,...,593.30,2.19,4,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0,0,0,0,0,9,1,1,0,0,...,542.40,2.00,3,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1,0,0,0,0,4,1,0,0,0,...,280.85,2.46,2,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,0,1,1,0,13,1,0,0,1,...,1237.85,3.27,5,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,1,1,1,0,3,1,0,0,0,...,267.40,2.80,3,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7016,0,1,0,0,0,13,1,0,1,0,...,742.90,1.84,3,0.0,0.0,1.0,0.0,0.0,0.0,1.0
7017,1,0,0,1,0,22,1,1,0,0,...,1873.70,2.84,3,1.0,0.0,0.0,0.0,0.0,1.0,0.0
7018,0,0,0,0,0,2,1,0,0,1,...,92.75,1.68,2,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7019,0,0,0,1,1,67,1,0,1,0,...,4627.65,2.26,5,0.0,0.0,0.0,1.0,0.0,0.0,1.0
7020,0,0,0,1,1,63,0,0,1,1,...,3707.60,1.97,5,0.0,0.0,0.0,1.0,0.0,1.0,0.0